
### Parameters in Data Loading and QC
time_params:
  interval : "1m" #use '5m' for 5 minutes
  period: "7d"

universe_params:
  universe_name: "tech_eqs"
  tech_eqs : [
    "TCS", 
    "INFY", 
    "MPHASIS", 
    "LTIM", 
    "COFORGE"
  ]

market_params: 
  time_zone: "Asia/Kolkata"
  start_time: "09:30"
  end_time: "15:30"


adf_testing_params:
  alpha: 0.05

### Parameters in Modelling VAR
var_params:
  max_lags: 10
  ic_criterion: "aic" # 'aic', 'bic', 'hqic', 'fpe'
  alpha: 0.05
  estimation_method: "ols"  # Options: 'ols', 'mle'

### Parameters in Signal Generator VAR
granger_causal_signal_gen_params:
  min_log_returns_threshold: 0.0005
  max_position_size: 1.0
  volatility_scaling: true
  target_volatility: 0.15